//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGail.GailService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cdssgailmodel.com/webservice", ConfigurationName="GailService.GailModelSoap")]
    public interface GailModelSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cdssgailmodel.com/webservice/CalculateProbability", ReplyAction="*")]
        double CalculateProbability(double a, double r1, double r2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cdssgailmodel.com/webservice/CalculateProbability", ReplyAction="*")]
        System.Threading.Tasks.Task<double> CalculateProbabilityAsync(double a, double r1, double r2);
        
        // CODEGEN: Generating message contract since element name agecat from namespace http://cdssgailmodel.com/webservice is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://cdssgailmodel.com/webservice/CalculateRR", ReplyAction="*")]
        WebApplicationGail.GailService.CalculateRRResponse CalculateRR(WebApplicationGail.GailService.CalculateRRRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cdssgailmodel.com/webservice/CalculateRR", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplicationGail.GailService.CalculateRRResponse> CalculateRRAsync(WebApplicationGail.GailService.CalculateRRRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateRRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateRR", Namespace="http://cdssgailmodel.com/webservice", Order=0)]
        public WebApplicationGail.GailService.CalculateRRRequestBody Body;
        
        public CalculateRRRequest() {
        }
        
        public CalculateRRRequest(WebApplicationGail.GailService.CalculateRRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cdssgailmodel.com/webservice")]
    public partial class CalculateRRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string agecat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string agemen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ageflb;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string nbiops;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string numrel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ah;
        
        public CalculateRRRequestBody() {
        }
        
        public CalculateRRRequestBody(string agecat, string agemen, string ageflb, string nbiops, string numrel, string ah) {
            this.agecat = agecat;
            this.agemen = agemen;
            this.ageflb = ageflb;
            this.nbiops = nbiops;
            this.numrel = numrel;
            this.ah = ah;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculateRRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculateRRResponse", Namespace="http://cdssgailmodel.com/webservice", Order=0)]
        public WebApplicationGail.GailService.CalculateRRResponseBody Body;
        
        public CalculateRRResponse() {
        }
        
        public CalculateRRResponse(WebApplicationGail.GailService.CalculateRRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://cdssgailmodel.com/webservice")]
    public partial class CalculateRRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double CalculateRRResult;
        
        public CalculateRRResponseBody() {
        }
        
        public CalculateRRResponseBody(double CalculateRRResult) {
            this.CalculateRRResult = CalculateRRResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GailModelSoapChannel : WebApplicationGail.GailService.GailModelSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GailModelSoapClient : System.ServiceModel.ClientBase<WebApplicationGail.GailService.GailModelSoap>, WebApplicationGail.GailService.GailModelSoap {
        
        public GailModelSoapClient() {
        }
        
        public GailModelSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GailModelSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GailModelSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GailModelSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CalculateProbability(double a, double r1, double r2) {
            return base.Channel.CalculateProbability(a, r1, r2);
        }
        
        public System.Threading.Tasks.Task<double> CalculateProbabilityAsync(double a, double r1, double r2) {
            return base.Channel.CalculateProbabilityAsync(a, r1, r2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplicationGail.GailService.CalculateRRResponse WebApplicationGail.GailService.GailModelSoap.CalculateRR(WebApplicationGail.GailService.CalculateRRRequest request) {
            return base.Channel.CalculateRR(request);
        }
        
        public double CalculateRR(string agecat, string agemen, string ageflb, string nbiops, string numrel, string ah) {
            WebApplicationGail.GailService.CalculateRRRequest inValue = new WebApplicationGail.GailService.CalculateRRRequest();
            inValue.Body = new WebApplicationGail.GailService.CalculateRRRequestBody();
            inValue.Body.agecat = agecat;
            inValue.Body.agemen = agemen;
            inValue.Body.ageflb = ageflb;
            inValue.Body.nbiops = nbiops;
            inValue.Body.numrel = numrel;
            inValue.Body.ah = ah;
            WebApplicationGail.GailService.CalculateRRResponse retVal = ((WebApplicationGail.GailService.GailModelSoap)(this)).CalculateRR(inValue);
            return retVal.Body.CalculateRRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplicationGail.GailService.CalculateRRResponse> WebApplicationGail.GailService.GailModelSoap.CalculateRRAsync(WebApplicationGail.GailService.CalculateRRRequest request) {
            return base.Channel.CalculateRRAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplicationGail.GailService.CalculateRRResponse> CalculateRRAsync(string agecat, string agemen, string ageflb, string nbiops, string numrel, string ah) {
            WebApplicationGail.GailService.CalculateRRRequest inValue = new WebApplicationGail.GailService.CalculateRRRequest();
            inValue.Body = new WebApplicationGail.GailService.CalculateRRRequestBody();
            inValue.Body.agecat = agecat;
            inValue.Body.agemen = agemen;
            inValue.Body.ageflb = ageflb;
            inValue.Body.nbiops = nbiops;
            inValue.Body.numrel = numrel;
            inValue.Body.ah = ah;
            return ((WebApplicationGail.GailService.GailModelSoap)(this)).CalculateRRAsync(inValue);
        }
    }
}
